language: java

jdk:
  - oraclejdk7
  - oraclejdk8
  - openjdk6
  - openjdk7

sudo: false

before_install:
  - mvn checkstyle:check
  
after_success:
  - mvn cobertura:cobertura
  - bash <(curl -s https://codecov.io/bash)
 
notifications: never
